import { today, timeNow } from '../utils/hmsHelpers';

export const SEED = [
  {
    id: "PAT-2026-00001", mrn: "MRN-2026-00001", queueNo: "Q-001", queueTime: "08:05",
    name: "Amara Okonkwo", phone: "+254-701-234-567", registeredDate: today(),
    status: "With Doctor",
    firstName: "Amara", middleName: "", lastName: "Okonkwo",
    dateOfBirth: "1990-03-15", gender: "Female", bloodGroup: "O+",
    maritalStatus: "Married", nationality: "Kenyan", occupation: "Teacher",
    altPhone: "", email: "amara@email.com",
    address: "12 Ngong Road", city: "Nairobi", county: "Nairobi", country: "Kenya",
    nokName: "Emeka Okonkwo", nokRel: "Spouse", nokPhone: "+254-702-345-678",
    ecSameNok: true, ecName: "Emeka Okonkwo", ecRel: "Spouse", ecPhone: "+254-702-345-678",
    category: "Insurance", insProvider: "SHA", insMemberNo: "SHA-2034-567890", insExpiry: "2026-12-31",
    corpOrg: "", corpId: "",
    consentTx: true, consentData: true,
    triage: {
      lv: "3", bp: "148/92", pulse: "82", temp: "36.8", rr: "18", spo2: "98", gcs: "15", wt: "68", ht: "163",
      complaint: "Persistent headache and dizziness for 3 days", nurse: "Nurse Adaeze Eze", time: "08:18"
    },
    billing: {
      invoiceNo: "INV-26-00001", receiptNo: "REC-26-00001", billedBy: "Jane Mwangi",
      billedAt: new Date(Date.now() - 3 * 3600000).toISOString(), paid: true, method: "SHA",
      items: [
        { id: "s1", name: "Consultation - General", price: 2500, qty: 1, cat: "consultation" },
        { id: "s5", name: "Lab - Basic Panel",       price: 3500, qty: 1, cat: "lab" },
      ],
      discount: 0, note: "",
    },
    clerking: {
      complaint: "Persistent headache and dizziness for 3 days",
      hpc: "Bilateral throbbing headache 7/10. Blurring of vision.",
      pmh: "Hypertension x5 years, poorly compliant", psh: "Appendicectomy 2012",
      fhx: "Father: HTN, stroke", shx: "Non-smoker. Teacher.",
      meds: "Amlodipine 5mg OD (missing doses)", allergies: "Penicillin - rash",
      exam: "BP 148/92 both arms. A/V nipping bilaterally.",
      provDx: "Hypertensive urgency", provCode: "I10",
      finalDx: "Hypertensive urgency", finalCode: "I10",
      differentials: "Migraine, Anxiety-related headache",
      plan: "Optimise antihypertensives. Check FBC, RFT, Electrolytes, UA.", disp: "OPD Follow-up",
      doctorName: "Dr. Obinna Nwosu", doctorReg: "MDCN-2019-04521", consNo: "CONS-26-00001",
      orders: {
        lab: { tests: ["l1","l8","l9","l18"], urgency: "Routine", notes: "End-organ damage screen." },
        rad: null,
        rx: {
          drugs: [
            { id: 1, name: "Amlodipine",  dose: "10mg", route: "Oral", freq: "OD (Once daily)",       duration: "Ongoing", instructions: "Morning. Do not stop suddenly." },
            { id: 2, name: "Losartan",    dose: "50mg", route: "Oral", freq: "OD (Once daily)",       duration: "Ongoing", instructions: "Monitor BP weekly." },
            { id: 3, name: "Paracetamol", dose: "1g",   route: "Oral", freq: "TDS (Three times daily)",duration: "5 days",  instructions: "For headache. Max 4g/day." },
          ],
        },
        consult: null,
      },
      labResults: {
        l1_hb:   { value: "11.8", unit: "g/dL",      flag: "low",    type: "num"  },
        l1_wbc:  { value: "7.2",  unit: "x10⁹/L",    flag: "normal", type: "num"  },
        l1_plt:  { value: "312",  unit: "x10⁹/L",    flag: "normal", type: "num"  },
        l1_pcv:  { value: "36",   unit: "%",           flag: "normal", type: "num"  },
        l1_mcv:  { value: "72",   unit: "fL",          flag: "low",    type: "num"  },
        l1_mchc: { value: "29",   unit: "g/dL",        flag: "low",    type: "num"  },
        l8_crea: { value: "88",   unit: "µmol/L",      flag: "normal", type: "num"  },
        l8_urea: { value: "5.4",  unit: "mmol/L",      flag: "normal", type: "num"  },
        l8_egfr: { value: "82",   unit: "mL/min",      flag: "normal", type: "num"  },
        l9_na:   { value: "139",  unit: "mmol/L",      flag: "normal", type: "num"  },
        l9_k:    { value: "3.4",  unit: "mmol/L",      flag: "low",    type: "num"  },
        l9_cl:   { value: "102",  unit: "mmol/L",      flag: "normal", type: "num"  },
        l9_bicarb:{ value: "24",  unit: "mmol/L",      flag: "normal", type: "num"  },
        l18_ua:  { value: "Protein +. RBCs +. pH 6.5. Leucocytes negative.", flag: "normal", type: "desc" },
      },
      labNo: "LAB-26-00001", labScientist: "MLT Tunde Afolabi",
      labCompletedAt: new Date(Date.now() - 20 * 60000).toISOString(), savedAt: new Date().toISOString(),
    },
  },
  {
    id: "PAT-2026-00002", mrn: "MRN-2026-00002", queueNo: "Q-002", queueTime: "10:05",
    name: "Kofi Mensah", phone: "+254-722-654-321", registeredDate: today(),
    status: "Lab Pending",
    firstName: "Kofi", middleName: "", lastName: "Mensah",
    dateOfBirth: "1958-09-30", gender: "Male", bloodGroup: "O+",
    maritalStatus: "Married", nationality: "Kenyan", occupation: "Farmer",
    altPhone: "", email: "",
    address: "Plot 14 Thika Road", city: "Nairobi", county: "Nairobi", country: "Kenya",
    nokName: "Akosua Mensah", nokRel: "Spouse", nokPhone: "+254-722-111-222",
    ecSameNok: true, ecName: "Akosua Mensah", ecRel: "Spouse", ecPhone: "+254-722-111-222",
    category: "Cash", insProvider: "", insMemberNo: "", insExpiry: "",
    corpOrg: "", corpId: "",
    consentTx: true, consentData: true,
    triage: {
      lv: "3", bp: "138/88", pulse: "76", temp: "36.6", rr: "17", spo2: "97", gcs: "15", wt: "74", ht: "170",
      complaint: "Polydipsia, polyuria, blurred vision for 3 weeks", nurse: "Nurse Adaeze Eze", time: "10:18"
    },
    billing: {
      invoiceNo: "INV-26-00002", receiptNo: "REC-26-00002", billedBy: "Jane Mwangi",
      billedAt: new Date(Date.now() - 60 * 60000).toISOString(), paid: true, method: "Cash",
      items: [
        { id: "s1", name: "Consultation - General", price: 2500, qty: 1, cat: "consultation" },
        { id: "s5", name: "Lab - Basic Panel",       price: 4500, qty: 1, cat: "lab" },
      ],
      discount: 0, note: "",
    },
    clerking: {
      complaint: "Polydipsia, polyuria, blurred vision for 3 weeks",
      hpc: "5-6L/day thirst, nocturia x4, 4kg weight loss.",
      pmh: "No known illness", psh: "None", fhx: "Father: T2DM", shx: "Non-smoker. Farmer.",
      meds: "None", allergies: "NKDA",
      exam: "Dehydrated. BMI 25.6. Bilateral microaneurysms on fundoscopy. BP 138/88.",
      provDx: "Type 2 Diabetes Mellitus - newly diagnosed", provCode: "E11.9",
      finalDx: "", finalCode: "", differentials: "T1DM, LADA",
      plan: "FBS, HbA1c, Lipids, RFT, UA. Start Metformin if eGFR adequate.", disp: "OPD Follow-up",
      doctorName: "Dr. Obinna Nwosu", doctorReg: "MDCN-2019-04521", consNo: "CONS-26-00002",
      orders: {
        lab: { tests: ["l4","l5","l6","l8","l18"], urgency: "Routine", notes: "Full metabolic panel." },
        rad: null,
        rx: {
          drugs: [
            { id: 1, name: "Metformin",   dose: "500mg", route: "Oral", freq: "BD (Twice daily)", duration: "Ongoing", instructions: "Take with meals." },
            { id: 2, name: "Amlodipine",  dose: "5mg",   route: "Oral", freq: "OD (Once daily)",  duration: "Ongoing", instructions: "Morning." },
            { id: 3, name: "Atorvastatin",dose: "20mg",  route: "Oral", freq: "Nocte",            duration: "Ongoing", instructions: "At night." },
          ],
        },
        consult: null,
      },
      labResults: null, savedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    },
  },
  {
    id: "PAT-2026-00003", mrn: "MRN-2026-00003", queueNo: "Q-003", queueTime: "07:45",
    name: "Zanele Dlamini", phone: "+254-733-234-567", registeredDate: today(),
    status: "Completed",
    firstName: "Zanele", middleName: "", lastName: "Dlamini",
    dateOfBirth: "1988-11-02", gender: "Female", bloodGroup: "B+",
    maritalStatus: "Single", nationality: "Kenyan", occupation: "Nurse",
    altPhone: "", email: "zanele.d@mater.co.ke",
    address: "7 Mombasa Road", city: "Nairobi", county: "Nairobi", country: "Kenya",
    nokName: "Thabo Dlamini", nokRel: "Brother", nokPhone: "+254-733-345-678",
    ecSameNok: true, ecName: "Thabo Dlamini", ecRel: "Brother", ecPhone: "+254-733-345-678",
    category: "Corporate", insProvider: "", insMemberNo: "", insExpiry: "",
    corpOrg: "Mater Hospital", corpId: "MAT-NRS-312",
    consentTx: true, consentData: true,
    triage: {
      lv: "4", bp: "118/76", pulse: "88", temp: "38.4", rr: "16", spo2: "99", gcs: "15", wt: "62", ht: "168",
      complaint: "Fever, dysuria, frequency for 2 days", nurse: "Nurse Bola Akinwale", time: "08:02"
    },
    billing: {
      invoiceNo: "INV-26-00003", receiptNo: "REC-26-00003", billedBy: "James Kariuki",
      billedAt: new Date(Date.now() - 4 * 3600000).toISOString(), paid: true, method: "Corporate Account",
      items: [
        { id: "s1",  name: "Consultation - General",  price: 2500, qty: 1, cat: "consultation" },
        { id: "s5",  name: "Lab - Basic Panel",        price: 2500, qty: 1, cat: "lab" },
        { id: "s10", name: "Pharmacy - Dispensing",    price: 500,  qty: 1, cat: "pharmacy" },
      ],
      discount: 0, note: "Mater Staff",
    },
    clerking: {
      complaint: "Fever, dysuria, frequency for 2 days",
      hpc: "Burning urination, frequency 12-15x/day, suprapubic pain, fever.",
      pmh: "Recurrent UTIs", psh: "None", fhx: "Non-contributory", shx: "Healthcare worker. OCP use.",
      meds: "Combined OCP", allergies: "Sulphonamides - Steven-Johnson syndrome",
      exam: "Febrile 38.4C. Suprapubic tenderness.",
      provDx: "Uncomplicated UTI", provCode: "N39.0",
      finalDx: "Acute Cystitis - E. coli", finalCode: "N30.00",
      differentials: "Pyelonephritis, PID",
      plan: "Oral antibiotics (avoid sulphonamides). Analgesia. Fluids.", disp: "OPD Follow-up",
      doctorName: "Dr. Adaeze Okeke", doctorReg: "MDCN-2020-05812", consNo: "CONS-26-00003",
      orders: {
        lab: { tests: ["l11","l18"], urgency: "Routine", notes: "MSU for C&S before antibiotics." },
        rad: null,
        rx: {
          drugs: [
            { id: 1, name: "Nitrofurantoin MR", dose: "100mg", route: "Oral", freq: "BD (Twice daily)",        duration: "5 days", instructions: "With food. Complete full course." },
            { id: 2, name: "Ibuprofen",          dose: "400mg", route: "Oral", freq: "TDS (Three times daily)", duration: "3 days", instructions: "With meals." },
            { id: 3, name: "Paracetamol",         dose: "1g",    route: "Oral", freq: "QDS (Four times daily)",  duration: "5 days", instructions: "Max 4g/day." },
          ],
        },
        consult: null,
      },
      labResults: {
        l11_uc: { value: "Significant growth - see sensitivity", flag: "high",   type: "qual" },
        l18_ua: { value: "Nitrites positive. Leucocytes +++. RBCs +.",            flag: "normal", type: "desc" },
      },
      labNo: "LAB-26-00003", labScientist: "MLT Chioma Obi",
      labCompletedAt: new Date(Date.now() - 120 * 60000).toISOString(),
      savedAt: new Date(Date.now() - 150 * 60000).toISOString(),
    },
  },
];
